name: PHPStan

on:
  pull_request:
    branches:
      - master

jobs:
  phpstan:
    uses: icinga/github-actions/.github/workflows/phpstan.yml@main
    with:
      dependencies: |
        {
          "/icingaweb2" : "https://github.com/Icinga/icingaweb2.git"
        }
